spring:
    application:
        name: facturation
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_HOSTNAME}
        password: ${DATABSE_PASSWORD}
        driver-class-name: org.postgresql.Driver
        jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true 


app:
    jwt:
        secret: ${JWT_SECRET}
        expiration: 3600000

server:
    port: 9090